version: 1

services:
  - type: web
    name: community-platform-backend
    env: python
    pythonVersion: "3.11.9" # Moved from envVars and placed here
    plan: starter
    region: oregon # It's good practice to specify the region
    
    # Use the more detailed build commands
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python -m alembic upgrade head
      
    # Use the more detailed start command from the deploy section
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    
    # Health check settings moved inside the service
    healthCheck:
      path: /health
      port: 8000 # Use the port your app listens on
      initialDelaySeconds: 30

    # Environment variables moved inside the service
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: community-platform-db
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: JWT_ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: ENVIRONMENT
        value: "production"
      - key: DEBUG
        value: "false"
      - key: CORS_ORIGINS
        value: "https://your-frontend-domain.vercel.app,https://your-custom-domain.com"
      - key: PORT
        value: "8000"

    # Scaling settings moved inside the service
    scaling:
      minInstances: 1
      maxInstances: 3
      targetCPUPercent: 70
      targetMemoryPercent: 80

databases:
  - name: community-platform-db
    plan: starter
    region: oregon # Match the region of your service